---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Marikina Polytechnic College EC2 Instance - CIS'

Resources:

  MPCCISInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0be48b687295f8bd6
      InstanceType: t3.xlarge
      KeyName: mpc-private-key
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            Encrypted: false
            DeleteOnTermination: true
            Iops: 3000
            SnapshotId: snap-0e78c6c71b35e19cb
            VolumeSize: 200
            VolumeType: gp3
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet: 
            - sg-05238fe2eb9ceff6a  # Using existing security group ID
          SubnetId: subnet-0f55ae49a27c8db75  # Ensure this subnet belongs to vpc-00acbe5616c6546b3
      CreditSpecification:
        CPUCredits: standard
      Tags:
        - Key: Name
          Value: Marikina Polytechnic College - CIS




Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MPCCISInstance
#WHITELISTING
WhitelistNewIP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-05238fe2eb9ceff6a
      IpProtocol: tcp
      FromPort: 22  # Example: Whitelisting SSH access
      ToPort: 22
      CidrIp: 203.0.113.50/32  # Replace with the new IP address you want to whitelist
      Description: Whitelisted IP for SSH accesss
